//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrviProjektniZadatakHCI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        public static global::System.Resources.ResourceManager resourceMan;
        
        public static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledpublicCode")]
        public SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrviProjektniZadatakHCI.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predmet.
        /// </summary>
        public static string _1Subject {
            get {
                return ResourceManager.GetString("1Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv predmeta.
        /// </summary>
        public static string _CourseNameText {
            get {
                return ResourceManager.GetString(" CourseNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno dodat.
        /// </summary>
        public static string _SuccessfullyAdded {
            get {
                return ResourceManager.GetString(" SuccessfullyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prisutan/Odsutan.
        /// </summary>
        public static string Absent_Present {
            get {
                return ResourceManager.GetString("Absent/Present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akademska godina mora da bude cjelobrojna vrijednost.
        /// </summary>
        public static string AcademicIntegerValue {
            get {
                return ResourceManager.GetString("AcademicIntegerValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akademsko zvanje.
        /// </summary>
        public static string AcademicTitleText {
            get {
                return ResourceManager.GetString("AcademicTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        public static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izbor entiteta za unos.
        /// </summary>
        public static string AddingEntity {
            get {
                return ResourceManager.GetString("AddingEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj Profesora.
        /// </summary>
        public static string AddProfessor {
            get {
                return ResourceManager.GetString("AddProfessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesor je zadužio kurs.
        /// </summary>
        public static string AssignMessage {
            get {
                return ResourceManager.GetString("AssignMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodijeli kurs.
        /// </summary>
        public static string AssignText {
            get {
                return ResourceManager.GetString("AssignText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled Prisustva.
        /// </summary>
        public static string AttendanceO {
            get {
                return ResourceManager.GetString("AttendanceO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vođenje evidencije o prisustvu.
        /// </summary>
        public static string AttendanceRecordMText {
            get {
                return ResourceManager.GetString("AttendanceRecordMText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled Prisustva.
        /// </summary>
        public static string AttendanceReviewText {
            get {
                return ResourceManager.GetString("AttendanceReviewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prisustvo.
        /// </summary>
        public static string AttendanceText {
            get {
                return ResourceManager.GetString("AttendanceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plava tema.
        /// </summary>
        public static string BlueText {
            get {
                return ResourceManager.GetString("BlueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promjene su poništene .
        /// </summary>
        public static string ChangesRetreved {
            get {
                return ResourceManager.GetString("ChangesRetreved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sifra.
        /// </summary>
        public static string CodeText {
            get {
                return ResourceManager.GetString("CodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi novu lozinku.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista predmeta.
        /// </summary>
        public static string CourseList {
            get {
                return ResourceManager.GetString("CourseList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trenutna lozinka nije tačna.
        /// </summary>
        public static string CurrentPassMessage {
            get {
                return ResourceManager.GetString("CurrentPassMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trenutna lozinka.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        public static string DateTimeText {
            get {
                return ResourceManager.GetString("DateTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rok.
        /// </summary>
        public static string DeadLineText {
            get {
                return ResourceManager.GetString("DeadLineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obriši.
        /// </summary>
        public static string DeleteText {
            get {
                return ResourceManager.GetString("DeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        public static string DescriptionText {
            get {
                return ResourceManager.GetString("DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECTS mora da bude cjelobrojna vrijednost.
        /// </summary>
        public static string ECTSIntegerValue {
            get {
                return ResourceManager.GetString("ECTSIntegerValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECTS.
        /// </summary>
        public static string ECTSText {
            get {
                return ResourceManager.GetString("ECTSText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailText {
            get {
                return ResourceManager.GetString("EmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engleski.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite ime predmeta.
        /// </summary>
        public static string EnterCourseName {
            get {
                return ResourceManager.GetString("EnterCourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite korisnika kojeg unosite.
        /// </summary>
        public static string EnteringUser {
            get {
                return ResourceManager.GetString("EnteringUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite lozinku.
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite korisničko ime.
        /// </summary>
        public static string EnterUsername {
            get {
                return ResourceManager.GetString("EnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška prilikom ažuriranja zadatka .
        /// </summary>
        public static string ErorrUpdatingTask {
            get {
                return ResourceManager.GetString("ErorrUpdatingTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Došlo je do greške prilikom dodavanja .
        /// </summary>
        public static string ErrorAdding {
            get {
                return ResourceManager.GetString("ErrorAdding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Došlo je do greške prilikom promjene lozinke.
        /// </summary>
        public static string ErrorChangePassword {
            get {
                return ResourceManager.GetString("ErrorChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška prilikom brisanja zadatka.
        /// </summary>
        public static string ErrorDeletingTask {
            get {
                return ResourceManager.GetString("ErrorDeletingTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesor nije zadužem na predmetu.
        /// </summary>
        public static string ErrorProfSubject {
            get {
                return ResourceManager.GetString("ErrorProfSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška prilikom razduživanja.
        /// </summary>
        public static string ErrorUnassign {
            get {
                return ResourceManager.GetString("ErrorUnassign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Došlo je do greške prilikom ažuriranja .
        /// </summary>
        public static string ErrorUpdate {
            get {
                return ResourceManager.GetString("ErrorUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum Ispita.
        /// </summary>
        public static string ExamDate {
            get {
                return ResourceManager.GetString("ExamDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum ispita.
        /// </summary>
        public static string ExamDateText {
            get {
                return ResourceManager.GetString("ExamDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite šifru zadatka:.
        /// </summary>
        public static string ExamIdText {
            get {
                return ResourceManager.GetString("ExamIdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ispiti.
        /// </summary>
        public static string ExamManagement {
            get {
                return ResourceManager.GetString("ExamManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ispiti po predmetima.
        /// </summary>
        public static string ExamsByCourses {
            get {
                return ResourceManager.GetString("ExamsByCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ispit.
        /// </summary>
        public static string ExamText {
            get {
                return ResourceManager.GetString("ExamText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popunite sva polja.
        /// </summary>
        public static string FillField {
            get {
                return ResourceManager.GetString("FillField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unos ocjena.
        /// </summary>
        public static string GradeEntry {
            get {
                return ResourceManager.GetString("GradeEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unos ocjena.
        /// </summary>
        public static string GradeEntryText {
            get {
                return ResourceManager.GetString("GradeEntryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled ocjena.
        /// </summary>
        public static string GradeReview {
            get {
                return ResourceManager.GetString("GradeReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocjena.
        /// </summary>
        public static string GradeText {
            get {
                return ResourceManager.GetString("GradeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zelena tema.
        /// </summary>
        public static string GreenText {
            get {
                return ResourceManager.GetString("GreenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domaci i Ispiti.
        /// </summary>
        public static string HomeworkExamText {
            get {
                return ResourceManager.GetString("HomeworkExamText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domaći zadaci.
        /// </summary>
        public static string Homeworks {
            get {
                return ResourceManager.GetString("Homeworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domaći zadatak.
        /// </summary>
        public static string HomeworkText {
            get {
                return ResourceManager.GetString("HomeworkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifikator već postoji.
        /// </summary>
        public static string IdExist {
            get {
                return ResourceManager.GetString("IdExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID  mora da bude cjelobrojna vrijednost.
        /// </summary>
        public static string IdIntegerValue {
            get {
                return ResourceManager.GetString("IdIntegerValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifikator.
        /// </summary>
        public static string IdText {
            get {
                return ResourceManager.GetString("IdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj indeksa.
        /// </summary>
        public static string IndexNumberText {
            get {
                return ResourceManager.GetString("IndexNumberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nevalidan unos ID ili akademske godine .
        /// </summary>
        public static string Invalid_ID_AY {
            get {
                return ResourceManager.GetString("Invalid_ID_AY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum predavanja.
        /// </summary>
        public static string LectureD {
            get {
                return ResourceManager.GetString("LectureD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijavi se.
        /// </summary>
        public static string LogInButton {
            get {
                return ResourceManager.GetString("LogInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijava.
        /// </summary>
        public static string LogInTitle {
            get {
                return ResourceManager.GetString("LogInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravljenje dodjelama.
        /// </summary>
        public static string ManageAssignmentText {
            get {
                return ResourceManager.GetString("ManageAssignmentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravljanje predmetima i aktivnostima.
        /// </summary>
        public static string ManagementSA {
            get {
                return ResourceManager.GetString("ManagementSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimalan broj bodova.
        /// </summary>
        public static string MaximumPointsText {
            get {
                return ResourceManager.GetString("MaximumPointsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesor je uspješno dodat.
        /// </summary>
        public static string MessageProfAdd {
            get {
                return ResourceManager.GetString("MessageProfAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        public static string NameText {
            get {
                return ResourceManager.GetString("NameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova lozinka.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nije selektovan profesor.
        /// </summary>
        public static string NoSelectedProfesoor {
            get {
                return ResourceManager.GetString("NoSelectedProfesoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nije selektovan predmet.
        /// </summary>
        public static string NoSubjectSelected {
            get {
                return ResourceManager.GetString("NoSubjectSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled prisustva po predmetima.
        /// </summary>
        public static string OAbyCourses {
            get {
                return ResourceManager.GetString("OAbyCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled aktivnosti i rezultata.
        /// </summary>
        public static string OverviewAR {
            get {
                return ResourceManager.GetString("OverviewAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} je ažuriran..
        /// </summary>
        public static string ParametarUpdate {
            get {
                return ResourceManager.GetString("ParametarUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  {1} je obrisan..
        /// </summary>
        public static string ParameterDelete {
            get {
                return ResourceManager.GetString("ParameterDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova lozinka i potvrda se ne podudaraju.
        /// </summary>
        public static string PassConfirmation {
            get {
                return ResourceManager.GetString("PassConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promjena lozinke.
        /// </summary>
        public static string PasswordChange {
            get {
                return ResourceManager.GetString("PasswordChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka je uspješno promijenjena.
        /// </summary>
        public static string PasswordChangeMessage {
            get {
                return ResourceManager.GetString("PasswordChangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka.
        /// </summary>
        public static string PasswordText {
            get {
                return ResourceManager.GetString("PasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postignuća po kursevima.
        /// </summary>
        public static string PerformanceByCourses {
            get {
                return ResourceManager.GetString("PerformanceByCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bodovi.
        /// </summary>
        public static string PointsText {
            get {
                return ResourceManager.GetString("PointsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prisutan.
        /// </summary>
        public static string PresentText {
            get {
                return ResourceManager.GetString("PresentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesor {0} {1} je obrisan.
        /// </summary>
        public static string ProfessorDeleted {
            get {
                return ResourceManager.GetString("ProfessorDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesor {0} {1} je ponovo dodat..
        /// </summary>
        public static string ProfessorReadded {
            get {
                return ResourceManager.GetString("ProfessorReadded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesor je uspješno ažuriran .
        /// </summary>
        public static string ProfessorSuccessfullyUpdated {
            get {
                return ResourceManager.GetString("ProfessorSuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesor.
        /// </summary>
        public static string ProfessorText {
            get {
                return ResourceManager.GetString("ProfessorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesor je uspješno ažuriran.
        /// </summary>
        public static string ProfUpdateMessage {
            get {
                return ResourceManager.GetString("ProfUpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unos prisustva.
        /// </summary>
        public static string RecordAttendance {
            get {
                return ResourceManager.GetString("RecordAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crvena tema.
        /// </summary>
        public static string RedText {
            get {
                return ResourceManager.GetString("RedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sačuvaj prisustvo.
        /// </summary>
        public static string SaveAttendanceButton {
            get {
                return ResourceManager.GetString("SaveAttendanceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sacuvaj.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite stavku za brisanje.
        /// </summary>
        public static string SelectItemDelete {
            get {
                return ResourceManager.GetString("SelectItemDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite profesora .
        /// </summary>
        public static string SelectProfessorText {
            get {
                return ResourceManager.GetString("SelectProfessorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite studenta.
        /// </summary>
        public static string SelectStudentText {
            get {
                return ResourceManager.GetString("SelectStudentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite predmet.
        /// </summary>
        public static string SelectSubjectText {
            get {
                return ResourceManager.GetString("SelectSubjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Srpski.
        /// </summary>
        public static string Serbian {
            get {
                return ResourceManager.GetString("Serbian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspjeh.
        /// </summary>
        public static string StudentAchievement {
            get {
                return ResourceManager.GetString("StudentAchievement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student {0} {1} je obrisan.
        /// </summary>
        public static string StudentDeleted {
            get {
                return ResourceManager.GetString("StudentDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studenti.
        /// </summary>
        public static string StudentList {
            get {
                return ResourceManager.GetString("StudentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} je uklonjen.
        /// </summary>
        public static string StudentRemoved_ {
            get {
                return ResourceManager.GetString("StudentRemoved ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student {0} {1} je vraćen..
        /// </summary>
        public static string StudentRestored {
            get {
                return ResourceManager.GetString("StudentRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        public static string StudentText {
            get {
                return ResourceManager.GetString("StudentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predmet je uspješno ažuriran .
        /// </summary>
        public static string SubjectSuccessfullyUpdated {
            get {
                return ResourceManager.GetString("SubjectSuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predmeti.
        /// </summary>
        public static string SubjectText {
            get {
                return ResourceManager.GetString("SubjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predmet je uspješno vraćen.
        /// </summary>
        public static string SubjectUndo {
            get {
                return ResourceManager.GetString("SubjectUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student je uspješno dodat.
        /// </summary>
        public static string SuccessAddStudent {
            get {
                return ResourceManager.GetString("SuccessAddStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predmet je uspješno dodat.
        /// </summary>
        public static string SuccessfulAddSubject {
            get {
                return ResourceManager.GetString("SuccessfulAddSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno obrisan.
        /// </summary>
        public static string SuccessfullyDelete {
            get {
                return ResourceManager.GetString("SuccessfullyDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesor je zadužen na predmet..
        /// </summary>
        public static string SuccessProfSubject {
            get {
                return ResourceManager.GetString("SuccessProfSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        public static string SurnameText {
            get {
                return ResourceManager.GetString("SurnameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postavljanje sistema.
        /// </summary>
        public static string SystemSetup {
            get {
                return ResourceManager.GetString("SystemSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifikator je zauzet .
        /// </summary>
        public static string TakenId {
            get {
                return ResourceManager.GetString("TakenId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadatak je uspješno dodat.
        /// </summary>
        public static string TaskAdd {
            get {
                return ResourceManager.GetString("TaskAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodavanje zadataka.
        /// </summary>
        public static string TaskAddText {
            get {
                return ResourceManager.GetString("TaskAddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadatak je ponovo dodat.
        /// </summary>
        public static string TaskAgainAdd {
            get {
                return ResourceManager.GetString("TaskAgainAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadatak je obrisan.
        /// </summary>
        public static string TaskDelete {
            get {
                return ResourceManager.GetString("TaskDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalji zadatka.
        /// </summary>
        public static string TaskDetails {
            get {
                return ResourceManager.GetString("TaskDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadatak nije uspješno dodat.
        /// </summary>
        public static string TaskErrorMessage {
            get {
                return ResourceManager.GetString("TaskErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv zadatka.
        /// </summary>
        public static string TaskNameText {
            get {
                return ResourceManager.GetString("TaskNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled zadataka.
        /// </summary>
        public static string TaskOverviewText {
            get {
                return ResourceManager.GetString("TaskOverviewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadatak je uspješno dodan.
        /// </summary>
        public static string TaskSuccessfullyAdd {
            get {
                return ResourceManager.GetString("TaskSuccessfullyAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadatak je uspješno obrisan.
        /// </summary>
        public static string TaskSuccessfullyDelete {
            get {
                return ResourceManager.GetString("TaskSuccessfullyDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadatak je uspješno ažuriran.
        /// </summary>
        public static string TaskSuccessfullyUpdate {
            get {
                return ResourceManager.GetString("TaskSuccessfullyUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip Zadatka.
        /// </summary>
        public static string TaskText {
            get {
                return ResourceManager.GetString("TaskText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razduži .
        /// </summary>
        public static string UnassignCourse {
            get {
                return ResourceManager.GetString("UnassignCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesor je razdužen sa predmeta.
        /// </summary>
        public static string UnassignMessage {
            get {
                return ResourceManager.GetString("UnassignMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nema dostupnih operacija za poništavanje.
        /// </summary>
        public static string UndoMessage {
            get {
                return ResourceManager.GetString("UndoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo: Profesor {0} {1} je vraćen..
        /// </summary>
        public static string UndoProfessorRestored {
            get {
                return ResourceManager.GetString("UndoProfessorRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuspješno dodavanje studenta.
        /// </summary>
        public static string UnsuccessfulStudent {
            get {
                return ResourceManager.GetString("UnsuccessfulStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predmet nije uspješno dodat .
        /// </summary>
        public static string UnsuccessSubject {
            get {
                return ResourceManager.GetString("UnsuccessSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ažuriraj.
        /// </summary>
        public static string UpdateButton {
            get {
                return ResourceManager.GetString("UpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberi entitet za  ažuriranje.
        /// </summary>
        public static string UpdateEntity {
            get {
                return ResourceManager.GetString("UpdateEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ažuriraj.
        /// </summary>
        public static string UpdateText {
            get {
                return ResourceManager.GetString("UpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime ili lozinka nisu validni.
        /// </summary>
        public static string UsernamePasswordInCorrect {
            get {
                return ResourceManager.GetString("UsernamePasswordInCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnicko ime.
        /// </summary>
        public static string UsernameText {
            get {
                return ResourceManager.GetString("UsernameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godina studija.
        /// </summary>
        public static string YearOfStudy {
            get {
                return ResourceManager.GetString("YearOfStudy", resourceCulture);
            }
        }
    }
}
